# Generated by Django 5.0.4 on 2024-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_pdfs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='available',
        ),
        migrations.AddField(
            model_name='course',
            name='max_participants',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, to='courses.pdffile'),
        ),
    ]
