# Generated by Django 5.0.4 on 2024-05-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='keywords',
        ),
    ]
